//GET API
GET http://localhost:3000/players


###POST API

POST http://localhost:3000/players
Content-Type: application/json

{
  "player_name": "Vishal",
  "jersey_number": 17,
  "role": "Bowler"
}

###GET API
GET http://localhost:3000/players/:playerId/
